set(_AMENT_PACKAGE_NAME "ik_solver")
set(ik_solver_VERSION "0.0.0")
set(ik_solver_MAINTAINER "Manuel Beschi <manuel.beschi@unibs.it>")
set(ik_solver_BUILD_DEPENDS "rclcpp" "tf2" "ik_solver_msgs" "pluginlib" "std_srvs" "geometry_msgs" "cnr_param" "cnr_logger" "ik_solver_core")
set(ik_solver_BUILDTOOL_DEPENDS "ament_cmake")
set(ik_solver_BUILD_EXPORT_DEPENDS "rclcpp" "tf2" "ik_solver_msgs" "pluginlib" "std_srvs" "geometry_msgs" "cnr_param" "cnr_logger" "ik_solver_core")
set(ik_solver_BUILDTOOL_EXPORT_DEPENDS )
set(ik_solver_EXEC_DEPENDS "rclcpp" "tf2" "ik_solver_msgs" "pluginlib" "std_srvs" "geometry_msgs" "cnr_param" "cnr_logger" "ik_solver_core")
set(ik_solver_TEST_DEPENDS )
set(ik_solver_GROUP_DEPENDS )
set(ik_solver_MEMBER_OF_GROUPS )
set(ik_solver_DEPRECATED "")
set(ik_solver_EXPORT_TAGS)
list(APPEND ik_solver_EXPORT_TAGS "<build_type condition=\"$ROS_VERSION == 2\">ament_cmake</build_type>")
list(APPEND ik_solver_EXPORT_TAGS "<build_type condition=\"$ROS_VERSION == 1\">catkin</build_type>")
